spring:
  application:
    name: microservice-discovery-nacos-stream-rabbitmq-consumer-1
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    stream:
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: consumer   #消费组，同一个组不重复消费同一条消息，适当增加消费组里面的消费者可以提高队列的消费速率
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:8080 # Sentinel 控制台地址
      filter:
        url-patterns: /** # 拦截请求的地址。默认为 /*
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds3:  # 自定义流控
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: FLOW
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: 127.0.0.1:8848 # Nacos 服务器地址
            namespace: # Nacos 命名空间
            group-id: DEFAULT_GROUP # Nacos 分组
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: FLOW # 规则类型
       # eager: true #立即加载
server:
  port: 18088 # 服务器端口。默认为 8080
feign:
  sentinel:
    enabled: true # 开启 Sentinel 对 Feign 的支持，默认为 false 关闭。
management:
  endpoints:
   web:
    exposure:
     include: "*"
  endpoint:
   health:
    show-details: always
