spring:
  application:
    name: microservice-discovery-nacos-stream-rabbitmq-provider-2
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        #bindings:
          #input:
            #consumer:
              #enabled: true # 是否开启消费，默认为 true
              #broadcasting: true # 是否使用广播消费，默认为 false（使用集群消费）
         #output:
           #producer:
           #group: output-group
      bindings:
        output:
          destination: test-topic1
          content-type: application/json
        #input:
          #destination: test-topic
          #content-type: application/json
          #group: test-group
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        dashboard: 127.0.0.1:8080 # Sentinel 控制台地址
      filter:
        url-patterns: /** # 拦截请求的地址。默认为 /*
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: 127.0.0.1:8848 # Nacos 服务器地址
            namespace: # Nacos 命名空间
            group-id: DEFAULT_GROUP # Nacos 分组
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: FLOW # 规则类型
server:
  port: 18086 # 服务器端口。默认为 8080
feign:
  sentinel:
    enabled: true # 开启 Sentinel 对 Feign 的支持，默认为 false 关闭。
management:
  endpoints:
   web:
    exposure:
     include: "*"
  endpoint:
   health:
    show-details: always